bump version, document changes for xfsinvutil interactive mode port from IRIX.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -152,6 +152,36 @@ AC_CHECK_LIB(uuid, uuid_generate,, [
 libuuid="/usr/lib/libuuid.a"
 AC_SUBST(libuuid)
 
+savedLIBS="$LIBS"
+savedCFLAGS="$CFLAGS"
+
+dnl Checks for curses header and library.
+AC_CHECK_HEADER(curses.h,, [
+	echo
+	echo 'FATAL ERROR: could not find a valid curses header.'
+	exit 1
+])
+AC_CHECK_LIB(curses, initscr,, [
+	echo
+	echo 'FATAL ERROR: could not find a valid curses library.'
+	exit 1
+])
+AC_MSG_CHECKING([for bad glibc/curses header interaction])
+libcurses="-lcurses"
+LIBS="$LIBS $libcurses"
+CFLAGS="$CFLAGS -D_GNU_SOURCE"
+AC_TRY_LINK([
+#include <curses.h>
+#include <signal.h>],
+	[wgetch(stdscr);],
+	[have_curses=yes; AC_MSG_RESULT([ok])],
+	[have_curses=no; libcurses=""; AC_MSG_RESULT([bad, disabling curses])])
+AC_SUBST(libcurses)
+AC_SUBST(have_curses)
+
+LIBS="$savedLIBS"
+CFLAGS="$savedCFLAGS"
+
 dnl Checks for base XFS headers and libraries.
 AC_CHECK_HEADER(xfs/libxfs.h,, [
 	echo
